services:
  - type: web
    name: ai-code-review-backend
    env: node
    region: ohio
    plan: starter
    rootDir: backend
    buildCommand: |
      npm install --include=dev
      ./node_modules/.bin/tsc -p tsconfig.prod.json || true
      # Create dist directory if it doesn't exist
      mkdir -p dist
      # Use tsc to compile any files that are not causing errors
      ./node_modules/.bin/tsc --skipLibCheck --noEmitOnError false -p tsconfig.prod.json
    startCommand: node dist/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
      - key: JWT_SECRET
        generateValue: true
      - key: GITHUB_WEBHOOK_SECRET
        generateValue: true
      - key: ANTHROPIC_API_KEY
        sync: false
      - key: GITHUB_CLIENT_ID
        sync: false
      - key: GITHUB_CLIENT_SECRET
        sync: false
      - key: FRONTEND_URL
        sync: false